# Generated by Django 5.2 on 2025-09-10 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom complet du client', max_length=100, verbose_name='Nom complet')),
                ('email', models.EmailField(db_index=True, max_length=100, unique=True, verbose_name='Email')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('address', models.TextField(max_length=200, verbose_name='Adresse')),
                ('ice', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='ICE')),
                ('is_company', models.BooleanField(default=False, verbose_name='Est une entreprise')),
                ('customer_type', models.CharField(choices=[('IND', 'Particulier'), ('COMP', 'Entreprise')], default='IND', max_length=4, verbose_name='Type de client')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['email'], name='customers_c_email_4fdeb3_idx'), models.Index(fields=['phone_number'], name='customers_c_phone_n_cabfe1_idx'), models.Index(fields=['name'], name='customers_c_name_f018e2_idx')],
            },
        ),
    ]
